---
- name: Add GitHub CLI Repo
  become: true
  ansible.builtin.deb822_repository:
    name: github-cli
    uris: https://cli.github.com/packages
    suites: stable
    components: main
    signed_by: https://cli.github.com/packages/githubcli-archive-keyring.gpg
- name: Install GitHub CLI
  become: true
  ansible.builtin.apt:
    name: gh
    state: present
    update_cache: true
